### ISSUE TITLE
'Invalid privileges, please check your API key.' when performing any GET requests

### ISSUE THREAD

**Issue by joshporter1** [hammackj/uirusu#15]
I discovered this issue when using the latest version of the gem to get comments for a file. My API key is valid, and the gem was working fine for other requests such as 'Uirusu::VTFile.query_report'. 

Upon investigating, I found out the underlying issue was line 49 of 'uirusu.rb'. This line was not sending the parameters properly, instead it was sending the params hash as additional headers. According to the [rest-client documentation](http://www.rubydoc.info/gems/rest-client/1.6.1/RestClient/Resource#get-instance_method), the first param for RestClient::Resource#get is `additional_headers` so our params were being merged in with the headers. 

The reason why RestClient::Resource#post still works, is because the first parameter is for the payload, so our params has still gets passed. 

This failure was not picked up by the tests because none of the test cases included a GET request.

**Comment by joshporter1** [comment]
I have a pull request incoming that includes the fix and an additional test case to include a GET request.

**Comment by hammackj** [comment]
Thanks for fixing this. Going to close it and push v1.1.1
